version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - test-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: vulnerable_password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
